var searchData=
[
  ['objdetect_20module_0',['Object Detection (objdetect module)',['../tutorial_table_of_content_objdetect.html',1,'tutorial_root']]],
  ['objdetect_20photo_20stitching_20video_1',['Other tutorials (ml, objdetect, photo, stitching, video)',['../tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['object_20detection_20objdetect_20module_2',['Object Detection (objdetect module)',['../tutorial_table_of_content_objdetect.html',1,'tutorial_root']]],
  ['opencv_3',['Introduction to OpenCV',['../tutorial_table_of_content_introduction.html',1,'tutorial_root']]],
  ['opencv_20ios_4',['OpenCV iOS',['../tutorial_table_of_content_ios.html',1,'tutorial_root']]],
  ['openqasmparser_5',['OpenQasmParser',['../classOpenQasmParser.html',1,'OpenQasmParser'],['../classOpenQasmParser.html#af06beb3cb699a6d6d5b9b6386d5f1a67',1,'OpenQasmParser::OpenQasmParser()']]],
  ['operation_2ecpp_6',['Operation.cpp',['../Operation_8cpp.html',1,'']]],
  ['operator_3c_3c_7',['operator&lt;&lt;',['../namespaceqc.html#aad3c741da63126bc5b446e1e527e4bc9',1,'qc::operator&lt;&lt;()'],['../namespacesym.html#a2d27e1c7397bd67d6a2b1ad006bd68ab',1,'sym::operator&lt;&lt;()']]],
  ['optimizer_2ecpp_8',['Optimizer.cpp',['../Optimizer_8cpp.html',1,'']]],
  ['optimizerrotationsinglegate_9',['OptimizerRotationSingleGate',['../classOptimizerRotationSingleGate.html',1,'OptimizerRotationSingleGate'],['../classOptimizerRotationSingleGate.html#a4e225d33fc7e806686f7e85fbe5780c2',1,'OptimizerRotationSingleGate::OptimizerRotationSingleGate()']]],
  ['optimizersinglegate_10',['OptimizerSingleGate',['../classOptimizerSingleGate.html',1,'OptimizerSingleGate'],['../classOptimizerSingleGate.html#af0668db661554b960d2ff98ff29f0307',1,'OptimizerSingleGate::OptimizerSingleGate()']]],
  ['originclassicalexpression_2ecpp_11',['OriginClassicalExpression.cpp',['../OriginClassicalExpression_8cpp.html',1,'']]],
  ['originclassicalsystem_2ecpp_12',['OriginClassicalSystem.cpp',['../OriginClassicalSystem_8cpp.html',1,'']]],
  ['originirerrorlistener_13',['OriginIRErrorListener',['../classOriginIRErrorListener.html',1,'']]],
  ['originirlexer_2ecpp_14',['originirLexer.cpp',['../originirLexer_8cpp.html',1,'']]],
  ['originirparser_2ecpp_15',['originirParser.cpp',['../originirParser_8cpp.html',1,'']]],
  ['originirtoqprog_2ecpp_16',['OriginIRToQProg.cpp',['../OriginIRToQProg_8cpp.html',1,'']]],
  ['originnoise_2ecpp_17',['OriginNoise.cpp',['../OriginNoise_8cpp.html',1,'']]],
  ['originphysicalqubit_2ecpp_18',['OriginPhysicalQubit.cpp',['../OriginPhysicalQubit_8cpp.html',1,'']]],
  ['originqmachinestatus_2ecpp_19',['OriginQMachineStatus.cpp',['../OriginQMachineStatus_8cpp.html',1,'']]],
  ['originqresult_2ecpp_20',['OriginQResult.cpp',['../OriginQResult_8cpp.html',1,'']]],
  ['originqubit_2ecpp_21',['OriginQubit.cpp',['../OriginQubit_8cpp.html',1,'']]],
  ['originqubitpool_2ecpp_22',['OriginQubitPool.cpp',['../OriginQubitPool_8cpp.html',1,'']]],
  ['originqvm_2ecpp_23',['OriginQVM.cpp',['../OriginQVM_8cpp.html',1,'']]],
  ['other_20tutorials_20ml_20objdetect_20photo_20stitching_20video_24',['Other tutorials (ml, objdetect, photo, stitching, video)',['../tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['output_5fmax_5fqnum_25',['OUTPUT_MAX_QNUM',['../SingleAmplitudeQVM_8cpp.html#a519a3a2685218aa2514f6499429e91f2',1,'SingleAmplitudeQVM.cpp']]]
];
